export const ERASMUS_COUNTRIES = [
  "Almanya",
  "Avusturya",
  "Belçika",
  "Bulgaristan",
  "Çek Cumhuriyeti",
  "Danimarka",
  "Estonya",
  "Finlandiya",
  "Fransa",
  "Hırvatistan",
  "Hollanda",
  "İrlanda",
  "İspanya",
  "İsveç",
  "İtalya",
  "İzlanda",
  "Kıbrıs",
  "Kuzey Makedonya",
  "Letonya",
  "Litvanya",
  "Lihtenştayn",
  "Lüksemburg",
  "Macaristan",
  "Malta",
  "Norveç",
  "Polonya",
  "Portekiz",
  "Romanya",
  "Sırbistan",
  "Slovakya",
  "Slovenya",
  "Türkiye",
  "Yunanistan",
] as const;
