export interface GlossaryTerm {
  term: string;
  definition: string;
}

export const IMPACT_GLOSSARY: GlossaryTerm[] = [
  { term: "Action Research", definition: "Planlama, eylem ve değerlendirmenin tekrarlanan döngüleri." },
  { term: "After Action Review (AAR)", definition: "Performansı değerlendirmek ve sonraki adımları iyileştirmek için faaliyet sonrası yapılan tartışma." },
  { term: "Beneficiary (Yararlanıcı)", definition: "Bir projeyi yürütmek için Erasmus+ fonu alan kuruluş." },
  { term: "Capacity Building Seminars", definition: "Beceri ve bilgiyi geliştirmeye yönelik oturumlar." },
  { term: "Community Feedback Mechanisms", definition: "Paydaşlardan gerçek zamanlı girdi toplama araçları." },
  { term: "Cross-Country Learning Sessions", definition: "Benzer kuruluşlar arasında bilgi paylaşımı." },
  { term: "Decision-Making Tree", definition: "Proje aşamaları için araç seçimine yön veren çerçeve." },
  { term: "Desired Outcome", definition: "Bir sürecin amaçlanan sonucu veya hedefi." },
  { term: "Effectiveness", definition: "Hedeflere ulaşmadaki başarı." },
  { term: "Efficiency", definition: "Hedeflere ulaşmak için kaynakların en uygun şekilde kullanılması." },
  { term: "Evaluation", definition: "Bir projenin kalitesinin veya etkisinin değerlendirilmesi." },
  { term: "Feedback Loops", definition: "Yinelemeli iyileştirmeler için sürekli paydaş girdisi." },
  { term: "Focus Group Interviews", definition: "Niteliksel içgörüler için yönlendirilmiş tartışmalar." },
  { term: "Goals (Hedefler)", definition: "Kısa vadeli proje niyetleri." },
  { term: "Impact (Etki)", definition: "Bir projenin sonucunda ortaya çıkan etkiler." },
  { term: "Impact (Long-term)", definition: "Bir projenin zaman içinde sürdürülen etkileri." },
  { term: "Impact (Negative)", definition: "Bir projenin sonucu olarak ortaya çıkan istenmeyen, kasıtsız etkiler." },
  { term: "Impact Mapping", definition: "Faaliyetler ile etkiler arasındaki bağlantıların diyagramla gösterilmesi." },
  { term: "Impact Pathway", definition: "Faaliyetleri hedeflere, hedefleri etkiye bağlayan adımlar." },
  { term: "Indicator (Gösterge)", definition: "İlerlemeyi veya sonuçları takip etmek için kullanılan niceliksel veya niteliksel bir ölçü." },
  { term: "Input (Girdi)", definition: "Bir projeye yatırılan kaynaklar veya bilgi." },
  { term: "Key Performance Indicator (KPI)", definition: "Hedefe ulaşmayı gösteren niceliksel ölçü." },
  { term: "Learning Outcome", definition: "Katılımcıların edindiği bilgi veya beceriler." },
  { term: "Living Learnings Document", definition: "Yansımaları ve iyi uygulamaları kaydeden, sürekli güncellenen belge." },
  { term: "Micro Follow-Up Surveys", definition: "Anında geri bildirim için kısa anketler." },
  { term: "Milestones (Kilometre Taşları)", definition: "İlerlemeyi işaretleyen önemli kazanımlar." },
  { term: "Monitoring (İzleme)", definition: "Proje faaliyetlerinin ve sonuçlarının sistematik takibi." },
  { term: "Most Significant Change (MSC)", definition: "Kritik proje sonuçlarını ortaya çıkarmak için hikayelerin toplanması." },
  { term: "Narrative Methods", definition: "Kişisel hikayelere odaklanan niteliksel yaklaşımlar." },
  { term: "Needs Assessment", definition: "Mevcut durum ile istenen durum arasındaki boşlukların belirlenmesi." },
  { term: "Negative Impact Monitoring", definition: "Bir projenin kasıtsız ve istenmeyen etkilerinin belirlenmesi ve belgelenmesi." },
  { term: "Objectives (Amaçlar)", definition: "Hedeflere ulaşmak için spesifik ve somut adımlar." },
  { term: "Online Impact Tools", definition: "Proje planlama ve değerlendirme için dijital kaynaklar." },
  { term: "Outcome (Sonuç)", definition: "Proje tarafından getirilen değişiklikler, çoğunlukla yararlanıcıların davranış değişikliği." },
  { term: "Outcome Harvesting", definition: "Sonuçların belirlenip faaliyetlere geri izlenmesi." },
  { term: "Outcome Mapping", definition: "Davranış veya ilişkilerdeki değişikliklerin izlenmesi." },
  { term: "Output (Çıktı)", definition: "Proje faaliyetlerinin doğrudan, somut sonuçları; genellikle geliştirilmiş (ama henüz kullanılmamış) beceri, deneyim veya materyaller." },
  { term: "Participatory Monitoring", definition: "Paydaş katılımına dayalı izleme süreçleri." },
  { term: "Participatory Rural Appraisal (PRA)", definition: "Topluluk odaklı veri toplama yöntemi." },
  { term: "Problem Tree Analysis", definition: "Kök nedenleri ve etkileri belirlemek için görsel araç." },
  { term: "Project Plan Canvas", definition: "Faaliyetleri, hedefleri ve kaynakları özetleyen çerçeve." },
  { term: "Purpose (Amaç)", definition: "Bir projenin ardındaki sebep veya niyet." },
  { term: "Qualitative Data", definition: "Tanımlayıcı, sayısal olmayan içgörüler." },
  { term: "Qualitative Indicators", definition: "Sayısal olmayan performans ölçüleri." },
  { term: "Qualitative Methods", definition: "Sayısal olmayan verileri analiz etme teknikleri." },
  { term: "Quantitative Data", definition: "Analiz için sayısal bilgi." },
  { term: "Quantitative Indicators", definition: "Yüzde gibi sayısal performans ölçüleri." },
  { term: "Quantitative Methods", definition: "Sayısal verileri analiz eden yaklaşımlar." },
  { term: "Realist Matrix", definition: "Farklı bağlamlarda nedensel mekanizmaları açıklığa kavuşturan araç." },
  { term: "Results-Based Management", definition: "Ölçülebilir sonuçlara öncelik veren yaklaşım." },
  { term: "Results Chain", definition: "Girdi, faaliyet, çıktı ve sonuçların sıralı bağlantısı." },
  { term: "Risk Register", definition: "Risklerin belirlenmesi, değerlendirilmesi ve azaltılması." },
  { term: "SMART Framework", definition: "Belirli, Ölçülebilir, Erişilebilir, İlgili ve Zaman sınırlı hedef belirleme yöntemi." },
  { term: "Status Quo", definition: "Mevcut durum veya temel durum." },
  { term: "Storytelling", definition: "Proje etkisini göstermek için anlatıların kullanılması." },
  { term: "Survey Tools", definition: "Katılımcılardan niceliksel veri toplama araçları." },
  { term: "Target Group (Hedef Grup)", definition: "Bir projenin amaçlanan birincil kitlesi veya katılımcıları." },
  { term: "Theory of Change (ToC)", definition: "Eylemleri istenen değişikliklere bağlayan çerçeve." },
  { term: "Triangulation", definition: "Bulguları doğrulamak için birden fazla yöntemin kullanılması." },
  { term: "Value (Değer)", definition: "Proje sonuçlarının önemi veya değeri." },
  { term: "Visual Reporting Tools", definition: "Etkiyi göstermek için diyagramlar ve görseller." },
  { term: "Volunteer Tracking Tools", definition: "Gönüllü katılımının ve etkisinin izlenmesi." },
  { term: "Workshops (Çalıştaylar)", definition: "Kapasite geliştirme ve yansıma için etkileşimli oturumlar." },
];
